import type { Config } from 'tailwindcss'
import { fontFamily } from 'tailwindcss/defaultTheme'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Exact palette from Figma
        'primary': '#001916',
        'on-primary': '#ffffff',
        'primary-fixed': '#b1eee4',
        'primary-fixed-dim': '#95d2c8',
        'on-primary-fixed': '#00201c',
        'on-primary-fixed-variant': '#095049',
        'primary-container': '#002f2b',
        'on-primary-container': '#5f9b92',
        'inverse-primary': '#95d2c8',
        'surface-tint': '#2b6860',
        'secondary': '#5d5e61',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2e2e5',
        'on-secondary-container': '#636467',
        'secondary-fixed': '#e2e2e5',
        'secondary-fixed-dim': '#c6c6c9',
        'on-secondary-fixed': '#1a1c1e',
        'on-secondary-fixed-variant': '#454749',
        'tertiary': '#16150f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#2b2923',
        'on-tertiary-container': '#949088',
        'tertiary-fixed': '#e8e2d9',
        'tertiary-fixed-dim': '#cbc6bd',
        'on-tertiary-fixed': '#1d1b16',
        'on-tertiary-fixed-variant': '#494640',
        'background': '#fcf9f8',
        'on-background': '#1c1b1b',
        'surface': '#fcf9f8',
        'on-surface': '#1c1b1b',
        'surface-variant': '#e5e2e1',
        'on-surface-variant': '#414848',
        'surface-bright': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'outline': '#717978',
        'outline-variant': '#c0c8c7',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['var(--font-newsreader)', ...fontFamily.serif],
        body: ['var(--font-inter)', ...fontFamily.sans],
        label: ['var(--font-inter)', ...fontFamily.sans],
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      maxWidth: {
        reading: '680px',
      },
      typography: (theme: (path: string) => string) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.on-surface'),
            '--tw-prose-headings': theme('colors.primary'),
            '--tw-prose-links': theme('colors.primary'),
            '--tw-prose-bold': theme('colors.primary'),
            '--tw-prose-quotes': theme('colors.on-surface-variant'),
            '--tw-prose-quote-borders': theme('colors.outline-variant'),
            '--tw-prose-code': theme('colors.primary'),
            '--tw-prose-hr': theme('colors.outline-variant'),
            '--tw-prose-bullets': theme('colors.outline'),
            '--tw-prose-counters': theme('colors.outline'),
            maxWidth: 'none',
            lineHeight: '1.75',
            fontSize: '1rem',
            fontFamily: 'var(--font-inter)',
            'h1, h2, h3, h4': {
              fontFamily: 'var(--font-newsreader)',
              fontWeight: '700',
              letterSpacing: '-0.02em',
              color: theme('colors.primary'),
            },
            h2: {
              fontSize: '1.5rem',
              marginTop: '3.5rem',
              marginBottom: '1rem',
            },
            h3: {
              fontSize: '1.2rem',
              fontWeight: '700',
              marginTop: '2.5rem',
              marginBottom: '0.5rem',
              fontFamily: 'var(--font-newsreader)',
            },
            a: {
              color: theme('colors.primary'),
              textDecoration: 'underline',
              textDecorationColor: theme('colors.outline-variant'),
              textUnderlineOffset: '3px',
              fontWeight: '400',
              '&:hover': {
                textDecorationColor: theme('colors.outline'),
              },
            },
            blockquote: {
              fontStyle: 'italic',
              borderLeftColor: theme('colors.outline-variant'),
              borderLeftWidth: '2px',
              color: theme('colors.on-surface-variant'),
              paddingLeft: '1.25rem',
            },
            'blockquote p:first-of-type::before': { content: 'none' },
            'blockquote p:last-of-type::after': { content: 'none' },
            hr: {
              borderColor: theme('colors.outline-variant'),
              opacity: '0.3',
            },
            code: {
              backgroundColor: theme('colors.surface-container-low'),
              borderRadius: '0px',
              padding: '0.15em 0.35em',
              fontSize: '0.875em',
              color: theme('colors.primary'),
            },
            'code::before': { content: 'none' },
            'code::after': { content: 'none' },
            'hr + p em': {
              display: 'block',
              fontStyle: 'normal',
              fontSize: '1.125rem',
              fontFamily: 'var(--font-newsreader)',
              fontWeight: '400',
              color: theme('colors.primary'),
              letterSpacing: '-0.01em',
              lineHeight: '1.4',
            },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
}

export default config
